# Site settings
title: Ingredients & Instructions
email: ingredients-and-instructions@forwarder.one
description: >
  Recipes, but only Ingredients and Instructions.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://wvdhouten.github.io" # the base hostname & protocol for your site
github_username: wvdhouten

# Build settings
markdown: kramdown
permalink: /:year/:title
